config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :menus
  get "catering", to: "menus#catering"
  get "info", to: "menus#info"
  get "reviews", to: "menus#reviews"

  resources :menu_items
  root "menus#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    render "index"
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @home = "index"
  end

  def catering
    @home = "catering"
  end

  def info
    @home = "info"
  end

  def reviews
    @home = "reviews"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :available, :vegan, :catering, :vegeterian, :featured)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_links.html.erb
<div class="col-2">

    <h5 class="link-container">
        <%= link_to "Home", root_path, class: "link #{@home == 'home' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Menu", "", class: "link #{@home == 'menu' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Catering", catering_path, class: "link #{@home== 'catering' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "More Info", info_path, class: "link #{@home == 'info' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Customer Reviews", "", class: "link #{@home == 'reviews' ? 'active' : ''}" %>
    </h5>


</div>

app/views/layouts/_title.html.erb
<div class="title-card">
    <h1 class="title-text">
        Chai-Sutta Bar
    </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Todo Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="<%= @menu %>-home">
        <div class="row page-container">
            <%= render 'layouts/links'%>
            <div class="col-8">
                <% unless @menu == "home"%>
                <%= render 'layouts/title'%>
                <% end %>
                <%= yield %>
            </div>
            <div class="col-2"></div>
        </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/menu_items/index.html.erb
<h1>This is Menu Item Page <h1>

app/views/menus/home.html.erb
<div class="col-8"></div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.text_field :available %>
  </div>

  <div class="field">
    <%= form.label :vegan %>
    <%= form.check_box :vegan %>
  </div>

  <div class="field">
    <%= form.label :catering %>
    <%= form.check_box :catering %>
  </div>

  <div class="field">
    <%= form.label :vegeterian %>
    <%= form.check_box :vegeterian %>
  </div>

  <div class="field">
    <%= form.label :featured %>
    <%= form.check_box :featured %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Available</th>
      <th>Vegan</th>
      <th>Catering</th>
      <th>Vegeterian</th>
      <th>Featured</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.available %></td>
        <td><%= product.vegan %></td>
        <td><%= product.catering %></td>
        <td><%= product.vegeterian %></td>
        <td><%= product.featured %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Available:</strong>
  <%= @product.available %>
</p>

<p>
  <strong>Vegan:</strong>
  <%= @product.vegan %>
</p>

<p>
  <strong>Catering:</strong>
  <%= @product.catering %>
</p>

<p>
  <strong>Vegeterian:</strong>
  <%= @product.vegeterian %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @product.featured %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>